name: CICD

on:
  push:
    branches:
    — master
    — dev
  pull_request:
    branches:
    — master
    — dev


jobs:
  # The "build" workflow
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.0' # The Go version to download (if necessary) and use.

      - name: Run testing
        run: go test ./...

